name: Convert Markdown to PDF
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc & LaTeX
        run: sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: pandoc README.md -o README.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: markdown-pdf
          path: README.pdf
